version: "3.5"

services:
  api01: &api
    container_name: api01
    image: degenozes/rinha:2024
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  api02:
    <<: *api
    container_name: api02

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rinha
      MYSQL_USER: rinha
      MYSQL_PASSWORD: rinha
    ports:
      - "3306:3306"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - mysql-vol:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "300MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

volumes:
  mysql-vol: